### PR TITLE
Add post for first RSE lunch

### PR DESCRIPTION
**Pull request by elanti**
I added a post to announce the first RSE lunch event. 

There are two weird things that I think @ineiti may have an answer to:
- It seems there is an inconsistency between the published website and the latest `main` branch. In the published pages there no events in the "Upcoming" section while on `main` there is still the "Kickoff meeting". This may be due to a missing update maybe?
- When testing the blog locally using `devbox run server`, I have a problem with the link in the "Upcoming meetings". The page exists because it is listed in the "Recent Posts" section.

Just to check that I didn't make any mistake with the workflow, I proceeded as follow to add the post. I used `devbox run hugo new content post/TITLE.md` to add the new post and then added the link manually in `_index.html` for the "Upcoming meetings".

Also, in the "Deploying the page" section of the `README.md` file, it is noted that it will pull the latest branch. Does this mean that it is not necessarily `main`? (just to make sure :) )

Thanks!

### CODE REVIEW

**Comment by ineiti** [comment]
> I added a post to announce the first RSE lunch event.

Thanks - so I can remove that from my TODO list :)

> * It seems there is an inconsistency between the published website and the latest `main` branch. In the published pages there no events in the "Upcoming" section while on `main` there is still the "Kickoff meeting". This may be due to a missing update maybe?

My bad - I forgot to push the latest changes. It should look like this:

https://github.com/c4dt/rse.epfl.ch/blob/add_rse_lunch_post_rebase/content/_index.html

> * When testing the blog locally using `devbox run server`, I have a problem with the link in the "Upcoming meetings". The page exists because it is listed in the "Recent Posts" section.

Yes, missing push. Rebase on main, fix the merge issues (or use the add_rse_lunch_post_rebase branch), and this should be OK (if I understood your comment correctly).

> Just to check that I didn't make any mistake with the workflow, I proceeded as follow to add the post. I used `devbox run hugo new content post/TITLE.md` to add the new post and then added the link manually in `_index.html` for the "Upcoming meetings".

Correct, that's the current way to use it.

> Also, in the "Deploying the page" section of the `README.md` file, it is noted that it will pull the latest branch. Does this mean that it is not necessarily `main`? (just to make sure :) )

You got them all right :) The cleanest way to do this would be with a github workflow when merging to `main`. But I didn't find out how to use the ftps with a token or something. Currently I'd have to add my EPFL password to github secrets, which I'm not willing to do. One thing I didn't write in the README is that I need to add you to the group who is allowed to push to the page (which I just did for your account). I added some more lines to the README - let me know if it is comprehensible.

**Comment by elanti** [comment]
Thanks Linus ! 
I updated my branch with the latest `main`.  Once it is accepted and merged, I will try to update it using the `README.md` instructions.

**Review by ineiti — APPROVED** [review]

**Comment by ineiti** [comment]
> Thanks Linus ! I updated my branch with the latest `main`. Once it is accepted and merged, I will try to update it using the `README.md` instructions.

Approved the PR - please go ahead and merge it.

**Comment by elanti** [comment]
Thanks ! 

It almost works :)

I tried uploading everything, but I get a lot of:
```
2024/05/22 10:48:04 ERROR : index.html: Failed to copy: update stor: 550 /rse.epfl.ch/index.html.fataxaj6.partial: No such file or directory
```
with debug info I get errors like:
```
2024/05/22 11:07:04 DEBUG : 404.html: Need to transfer - File not found at Destination
```
Like if the folder `/rse.epfl.ch` didn't exist. Unfortunately, I could not connect to the machine to check that.

While I solve the issue, would you mind updating the website? Please, excuse me for the inconvenience...

**Comment by ineiti** [comment]
Done. Thanks a lot for making sure the update doesn't only work on my computer :) Even though I think that @PascalinDe already updated it from hers, too.

I opened #8 to check what went wrong. I copied my `rclone.conf` - have a look if it is different.

Also, you linked using uppercase letters, which [works on mac](https://web.archive.org/web/20150112214037/https://plus.google.com/+JunioCHamano/posts/1Bpaj3e3Rru) (scroll down to Linus' second comment), but doesn't work on the webserver, which is on linux. I fixed that.

**Comment by elanti** [comment]
>I opened https://github.com/c4dt/rse.epfl.ch/issues/8 to check what went wrong. I copied my rclone.conf - have a look if it is different.

I will have a look at it!

> Also, you linked using uppercase letters, which [works on mac](https://web.archive.org/web/20150112214037/https://plus.google.com/+JunioCHamano/posts/1Bpaj3e3Rru) (scroll down to Linus' second comment), but doesn't work on the webserver, which is on linux. I fixed that.

OK, that was the problem... Thanks !

**Pull request merged**
