### PR TITLE
feat: add Spring '24 Open Source Service Meet Up recap

### PR DESCRIPTION
**Pull request by PascalinDe**
add brief recap of Spring '24 Open Source Services Meet Up

I hope that this is correct - for some reason, the server is correctly starting but only returning 401 (everything builds fine though)...

### CODE REVIEW

**Comment by ineiti** [comment]
Rebase on the latest `main`, and `devbox run server` will install the git submodule.

**Comment by ineiti** [comment]
Please add:

- number of participants
- speaker names
- estimate of next meeting (6 months -> after Summer)

**Comment by PascalinDe** [comment]
> Please add:
> 
>     * number of participants
> 
>     * speaker names
> 
>     * estimate of next meeting (6 months -> after Summer)

done

**Review by ineiti — APPROVED** [review]
Great - thanks a lot. If you want to try to push it, you'll have to have the config file something like this:

```bash
$ cat ~/.config/rclone/rclone.conf 
[ic-ftps]
type = ftp
host = ic-ftps.epfl.ch
pass = $( echo "secretpassword" | rclone obscure - )
tls = false
explicit_tls = true
```

I think the pass is your EPFL Gaspar password. EPFL doesn't provide an access-token based login for this service.

After you should be able to update it with

```bash
devbox run update
```

**Pull request merged**
